Yeonju
i-go-algo/i-go-algo pull request #3
Opened 2022-06-24 13:01 UTC by vanellotree

## ✏ Problems

- [BOJ] 01003 - 피보나치 함수
- [BOJ] 01012 유기농 배추

<br />
<br />

## 💡 Idea & Algorithm 

### 피보나치 함수: 
- 1은 (0, 1), 0 은 (1,0) 이후 함수들은 그 전의 값들 더해주며 일일이 저장
- 튜플로 저장해서 그런가 시간이 72ms 나왔습니다.

### 유기농 배추:
_ bfs 기본형
- bfs 로 연결된 1(배추밭)들의 총 개수를 세면 됩니다.

<br />
<br />

## ⏰ Efficiency 

- 72ms (Python3)
- 104 (Python3)

<br />
<br />

## 💬 Comment 

유기농 배추 문제 되게 오래전에 풀어 봤는데 간만에 푸니까 훨씬 쉽게 풀리긴하네요 
근데 n 과 m 가로 세로가 왜 떄문인지 안 맞아서 조금 고생은 했네요.. ㅂㄷㅂㄷ

2022-06-24 14:13 UTC, kargo0825 commented on BOJ/01003-피보나치_함수/01003-피보나치_함수-yeonju.py
> +
와! 좋습니다!
근데 이거 n이 40 이하라고 명시가 되어있어서 for문 밖에서 한번만 40짜리 만든다음에 for문 안에서는 print만 해도 되더라구요! 시간을 아낄 수 있을 겁니다!

2022-06-24 14:25 UTC, kargo0825 commented on BOJ/01003-피보나치_함수/01003-피보나치_함수-yeonju.py
> +    print(fibo[n][0], end=' ')
```suggestion
    print(fibo[n][0], fino[n][1])
```
이거 띄어쓰기로만 구분할꺼면 end=" " 안하고 콤마로만 구분해도 됩니다!

2022-06-24 14:28 UTC, kargo0825 requested changes

2022-06-24 14:28 UTC, kargo0825 commented on BOJ/01003-피보나치_함수/01003-피보나치_함수-yeonju.py
> +    print(fibo[n][0], end=' ')
```suggestion
    print(fibo[n][0], fibo[n][1])
```
요롷게 하고 아래줄을 지워보죠!

2022-06-24 14:28 UTC, kargo0825 commented on BOJ/01003-피보나치_함수/01003-피보나치_함수-yeonju.py
> +    print(fibo[n][1])
```suggestion
```

2022-06-29 11:55 UTC, kargo0825 commented on BOJ/01107-리모컨/01107-리모컨-yeonju.py
> +for num in range(1000000):
세상에! 난 무슨짓을 하고있던거지!
그냥 싹다 돌려보면 되는거였군요!

2022-06-29 13:55 UTC, kargo0825 approved these changes

2022-06-29 14:01 UTC, Eonyong approved these changes

2022-06-29 14:57 UTC, merged